In [ ]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

# ndarray


### 개요

In [2]:
import numpy as np


array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 shape:', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 shape:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 shape:', array3.shape)

print('array: {0}차원, array2 : {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)
array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 shape: (1, 3)
array: 1차원, array2 : 2차원, array3: 2차원


### 데이터 타입

In [23]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print('array1:', array1, array1.dtype)

list2 = [1, 2, 'test']
array2 = np.array(list2)
print('array2:', array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print('array3:', array3, array3.dtype)

array_int1 = np.array([1, 2, 3])
print(array_int1, array_int1.dtype)

# array_int1 (int) -> array_float1 (float)
array_float1 = array_int1.astype('float64')
print(array_float1, array_float1.dtype)

# array_float1 (float) -> array_int2 (int)
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

array_float2 = np.array([1.1, 2.1, 3.1])
print(array_float2, array_float2.dtype)

# array_float2 (float) -> array_int3 (int)
array_int3 = array_float2.astype('int32')
print(array_int3, array_int3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
array1: [1 2 3] int64
array2: ['1' '2' 'test'] <U21
array3: [1. 2. 3.] float64
[1 2 3] int64
[1. 2. 3.] float64
[1 2 3] int32
[1.1 2.1 3.1] float64
[1 2 3] int32


### arange, zeros, ones

In [28]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [33]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array2.reshape(5, 2)
print('array3:\n', array3)

array4 = array1.reshape(-1, 5)
print('array4:\n', array4)

array5 = array2.reshape(5, -1)
print('array5:\n', array5)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array5:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [37]:
array6 = np.arange(8)
print('array6:\n', array6)

array7 = array6.reshape((2, 2, 2))
print('array7:\n', array7)
print(array7.tolist())

array8 = array6.reshape(-1, 1)
print('array8:\n', array8)

array6:
 [0 1 2 3 4 5 6 7]
array7:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array8:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


### indexing